# Generated by Django 2.1.5 on 2019-11-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191107_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.CharField(default='R-001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_ref_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
