# Generated by Django 2.1.5 on 2019-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(max_length=10)),
                ('checkin_date', models.DateField(blank=True)),
                ('checkin_time', models.TimeField(blank=True)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='resbooking',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resbooking',
            name='user_ref_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resbooking',
            name='booking_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resbooking',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
