# Generated by Django 2.1.5 on 2019-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191107_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='resbooking',
            name='table_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
