# Generated by Django 2.1.5 on 2019-11-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_resbooking_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
